version: "3.9"

services:
  api:
    build: .
    container_name: nestjs-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:latest
    container_name: mysql-db-stilo-kids
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
